# Generated by Django 5.0.6 on 2025-05-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=50)),
                ("date", models.DateField()),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
                ("cancelled", models.BooleanField(default=False)),
                ("rescheduled", models.BooleanField(default=False)),
                ("rescheduled_date", models.DateField(blank=True, null=True)),
                ("rescheduled_time", models.TimeField(blank=True, null=True)),
                ("rescheduled_reason", models.TextField(blank=True, null=True)),
                ("appointment_time", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["date", "appointment_time"],
                        name="doctor_appo_date_991be5_idx",
                    )
                ],
            },
        ),
    ]
