# Generated by Django 5.1.3 on 2025-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Rescheduled", "Rescheduled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
