# Generated by Django 5.1.3 on 2025-09-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="replied",
            field=models.BooleanField(default=False),
        ),
    ]
