# Generated by Django 5.1.3 on 2025-09-17 16:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0008_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
