# Generated by Django 5.1.3 on 2025-09-17 19:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0010_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Enter icon class e.g. 'bi bi-clipboard2-heart' or 'fas fa-baby'",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
